# Generated by Django 5.0.2 on 2024-02-29 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='lastname',
        ),
    ]
