# Generated by Django 5.0.2 on 2024-02-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_remove_branch_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='Ваше значение по умолчанию для адреса', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='position',
            field=models.CharField(default='Пример позиции', max_length=255, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.CharField(default='Не указан', max_length=255, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
