# Generated by Django 5.0.2 on 2024-02-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0003_remove_branch_location_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='data',
            field=models.DateTimeField(default=2, max_length=250, verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(default=' адреса', max_length=255),
        ),
        migrations.AlterField(
            model_name='branch',
            name='position',
            field=models.IntegerField(default='Пример позиции', max_length=255, verbose_name='Позиция'),
        ),
    ]
