# Generated by Django 5.0.2 on 2024-03-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_branch_data_alter_branch_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='data',
            field=models.DateTimeField(max_length=250, verbose_name='ВВЕДИТЕ ЧАСЫ В ФОРМАТЕ ЧЧ:ММ ПРИМЕР 15:30'),
        ),
    ]
