# Generated by Django 5.0.2 on 2024-03-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0006_alter_branch_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
