# Generated by Django 5.0.2 on 2024-03-01 03:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0007_alter_branch_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
